In [12]:
import polars as pl
from pprint import pprint

In [6]:
data = pl.scan_ndjson("../data/raw/arxiv-metadata-oai-snapshot.json")

In [8]:
data.head().collect()

shape: (5, 14)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id        ┆ submitter ┆ authors   ┆ title     ┆ … ┆ abstract  ┆ versions  ┆ update_da ┆ authors_ │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ te        ┆ parsed   │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ str       ┆ list[stru ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆ ct[2]]    ┆ str       ┆ list[lis │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ t[str]]  │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0704.0001 ┆ Pavel     ┆ C.        ┆ Calculati ┆ … ┆ A fully   ┆ [{"v1","M ┆ 2008-11-2 ┆ [["Baláz │
│           ┆ Nadolsky  ┆ Bal\'azs, ┆ on of     ┆   ┆ different ┆ on, 2 Apr ┆ 6         ┆ s",      │
│           ┆           ┆ E. L.     ┆ prompt    ┆   ┆ ial       ┆ 2007      ┆           ┆ "C.",    │
│           ┆           ┆ Berger,   ┆ diphoton… ┆   ┆ calcula…  ┆ 19:18:…   ┆           ┆ ""],     │
│           ┆           ┆ P. …      ┆           ┆   ┆           ┆           ┆           ┆ ["Berge… │
│ 0704.0002 ┆ Louis     ┆ Ileana    ┆ Sparsity- ┆ … ┆ We        ┆ [{"v1","S ┆ 2008-12-1 ┆ [["Strei │
│           ┆ Theran    ┆ Streinu   ┆ certifyin ┆   ┆ describe  ┆ at, 31    ┆ 3         ┆ nu", "Il │
│           ┆           ┆ and Louis ┆ g Graph   ┆   ┆ a new alg ┆ Mar 2007  ┆           ┆ eana",   │
│           ┆           ┆ Thera…    ┆ Deco…     ┆   ┆ orithm,…  ┆ 02:26…    ┆           ┆ ""], ["… │
│ 0704.0003 ┆ Hongjun   ┆ Hongjun   ┆ The       ┆ … ┆ The       ┆ [{"v1","S ┆ 2008-01-1 ┆ [["Pan", │
│           ┆ Pan       ┆ Pan       ┆ evolution ┆   ┆ evolution ┆ un, 1 Apr ┆ 3         ┆ "Hongjun │
│           ┆           ┆           ┆ of the    ┆   ┆ of Earth- ┆ 2007      ┆           ┆ ", ""]]  │
│           ┆           ┆           ┆ Earth-Moo ┆   ┆ Moon …    ┆ 20:46:…   ┆           ┆          │
│           ┆           ┆           ┆ …         ┆   ┆           ┆           ┆           ┆          │
│ 0704.0004 ┆ David     ┆ David     ┆ A determi ┆ … ┆ We show   ┆ [{"v1","S ┆ 2007-05-2 ┆ [["Calla │
│           ┆ Callan    ┆ Callan    ┆ nant of   ┆   ┆ that a    ┆ at, 31    ┆ 3         ┆ n",      │
│           ┆           ┆           ┆ Stirling  ┆   ┆ determina ┆ Mar 2007  ┆           ┆ "David", │
│           ┆           ┆           ┆ cycl…     ┆   ┆ nt o…     ┆ 03:16…    ┆           ┆ ""]]     │
│ 0704.0005 ┆ Alberto   ┆ Wael Abu- ┆ From      ┆ … ┆ In this   ┆ [{"v1","M ┆ 2013-10-1 ┆ [["Abu-S │
│           ┆ Torchinsk ┆ Shammala  ┆ dyadic    ┆   ┆ paper we  ┆ on, 2 Apr ┆ 5         ┆ hammala" │
│           ┆ y         ┆ and       ┆ $\Lambda_ ┆   ┆ show how  ┆ 2007      ┆           ┆ ,        │
│           ┆           ┆ Alberto … ┆ {\alpha}$ ┆   ┆ to…       ┆ 18:09:…   ┆           ┆ "Wael",  │
│           ┆           ┆           ┆ …         ┆   ┆           ┆           ┆           ┆ ""],…    │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [13]:
columns = data.columns
pprint(columns)

['id',
 'submitter',
 'authors',
 'title',
 'comments',
 'journal-ref',
 'doi',
 'report-no',
 'categories',
 'license',
 'abstract',
 'versions',
 'update_date',
 'authors_parsed']

/var/folders/0m/rh70gs7d34l46d2kb6f6nzjr0000gn/T/ipykernel_24008/2846330830.py:1: PerformanceWarning: Determining the column names of a LazyFrame requires resolving its schema, which is a potentially expensive operation. Use `LazyFrame.collect_schema().names()` to get the column names without this warning.
  columns = data.columns

In [15]:
data.count().collect()

shape: (1, 14)
┌─────────┬───────────┬─────────┬─────────┬───┬──────────┬──────────┬─────────────┬────────────────┐
│ id      ┆ submitter ┆ authors ┆ title   ┆ … ┆ abstract ┆ versions ┆ update_date ┆ authors_parsed │
│ ---     ┆ ---       ┆ ---     ┆ ---     ┆   ┆ ---      ┆ ---      ┆ ---         ┆ ---            │
│ u32     ┆ u32       ┆ u32     ┆ u32     ┆   ┆ u32      ┆ u32      ┆ u32         ┆ u32            │
╞═════════╪═══════════╪═════════╪═════════╪═══╪══════════╪══════════╪═════════════╪════════════════╡
│ 3021763 ┆ 3006578   ┆ 3021763 ┆ 3021763 ┆ … ┆ 3021763  ┆ 3021763  ┆ 3021763     ┆ 3021763        │
└─────────┴───────────┴─────────┴─────────┴───┴──────────┴──────────┴─────────────┴────────────────┘

In [16]:
abstract_lengths = data.select(pl.col("abstract").str.len_chars().alias("abstract_length"))

In [18]:
abstract_lengths.describe()

shape: (9, 2)
┌────────────┬─────────────────┐
│ statistic  ┆ abstract_length │
│ ---        ┆ ---             │
│ str        ┆ f64             │
╞════════════╪═════════════════╡
│ count      ┆ 3.021763e6      │
│ null_count ┆ 0.0             │
│ mean       ┆ 997.172098      │
│ std        ┆ 433.514097      │
│ min        ┆ 3.0             │
│ 25%        ┆ 660.0           │
│ 50%        ┆ 978.0           │
│ 75%        ┆ 1314.0          │
│ max        ┆ 6091.0          │
└────────────┴─────────────────┘

In [24]:
valid_abstracts = data.filter(pl.col("abstract").str.len_chars() > 150).select(pl.len()).collect()

In [25]:
valid_abstracts

shape: (1, 1)
┌─────────┐
│ len     │
│ ---     │
│ u32     │
╞═════════╡
│ 2999409 │
└─────────┘