In [11]:
import polars as pl
import numpy as np

In [2]:
df = pl.scan_parquet("../data/processed/arxiv_quantized_embeddings_4bits_qjl.parquet")

In [3]:
df.schema

/var/folders/0m/rh70gs7d34l46d2kb6f6nzjr0000gn/T/ipykernel_5540/3182147272.py:1: PerformanceWarning: Resolving the schema of a LazyFrame is a potentially expensive operation. Use `LazyFrame.collect_schema()` to get the schema without this warning.
  df.schema

Schema([('id', String),
        ('packed_embedding', Array(UInt8, shape=(256,))),
        ('gamma', Float32),
        ('packed_qjl_bits', Array(UInt8, shape=(64,)))])

In [4]:
df.head().collect()

shape: (5, 4)
┌───────────┬───────────────────┬──────────┬─────────────────┐
│ id        ┆ packed_embedding  ┆ gamma    ┆ packed_qjl_bits │
│ ---       ┆ ---               ┆ ---      ┆ ---             │
│ str       ┆ array[u8, 256]    ┆ f32      ┆ array[u8, 64]   │
╞═══════════╪═══════════════════╪══════════╪═════════════════╡
│ 0704.0001 ┆ [101, 150, … 118] ┆ 0.089538 ┆ [27, 77, … 123] │
│ 0704.0002 ┆ [40, 199, … 173]  ┆ 0.084131 ┆ [51, 8, … 100]  │
│ 0704.0003 ┆ [162, 75, … 102]  ┆ 0.086626 ┆ [16, 35, … 103] │
│ 0704.0004 ┆ [33, 124, … 68]   ┆ 0.08507  ┆ [1, 129, … 19]  │
│ 0704.0005 ┆ [125, 47, … 100]  ┆ 0.093959 ┆ [114, 11, … 37] │
└───────────┴───────────────────┴──────────┴─────────────────┘

In [8]:
raw = pl.scan_parquet("../data/raw/arxiv-metadata-oai-snapshot.parquet")

In [9]:
raw.head().collect()

shape: (5, 14)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id        ┆ submitter ┆ authors   ┆ title     ┆ … ┆ abstract  ┆ versions  ┆ update_da ┆ authors_ │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ te        ┆ parsed   │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ str       ┆ list[stru ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆ ct[2]]    ┆ str       ┆ list[lis │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ t[str]]  │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0704.0001 ┆ Pavel     ┆ C.        ┆ Calculati ┆ … ┆ A fully   ┆ [{"v1","M ┆ 2008-11-2 ┆ [["Baláz │
│           ┆ Nadolsky  ┆ Bal\'azs, ┆ on of     ┆   ┆ different ┆ on, 2 Apr ┆ 6         ┆ s",      │
│           ┆           ┆ E. L.     ┆ prompt    ┆   ┆ ial       ┆ 2007      ┆           ┆ "C.",    │
│           ┆           ┆ Berger,   ┆ diphoton… ┆   ┆ calcula…  ┆ 19:18:…   ┆           ┆ ""],     │
│           ┆           ┆ P. …      ┆           ┆   ┆           ┆           ┆           ┆ ["Berge… │
│ 0704.0002 ┆ Louis     ┆ Ileana    ┆ Sparsity- ┆ … ┆ We        ┆ [{"v1","S ┆ 2008-12-1 ┆ [["Strei │
│           ┆ Theran    ┆ Streinu   ┆ certifyin ┆   ┆ describe  ┆ at, 31    ┆ 3         ┆ nu", "Il │
│           ┆           ┆ and Louis ┆ g Graph   ┆   ┆ a new alg ┆ Mar 2007  ┆           ┆ eana",   │
│           ┆           ┆ Thera…    ┆ Deco…     ┆   ┆ orithm,…  ┆ 02:26…    ┆           ┆ ""], ["… │
│ 0704.0003 ┆ Hongjun   ┆ Hongjun   ┆ The       ┆ … ┆ The       ┆ [{"v1","S ┆ 2008-01-1 ┆ [["Pan", │
│           ┆ Pan       ┆ Pan       ┆ evolution ┆   ┆ evolution ┆ un, 1 Apr ┆ 3         ┆ "Hongjun │
│           ┆           ┆           ┆ of the    ┆   ┆ of Earth- ┆ 2007      ┆           ┆ ", ""]]  │
│           ┆           ┆           ┆ Earth-Moo ┆   ┆ Moon …    ┆ 20:46:…   ┆           ┆          │
│           ┆           ┆           ┆ …         ┆   ┆           ┆           ┆           ┆          │
│ 0704.0004 ┆ David     ┆ David     ┆ A determi ┆ … ┆ We show   ┆ [{"v1","S ┆ 2007-05-2 ┆ [["Calla │
│           ┆ Callan    ┆ Callan    ┆ nant of   ┆   ┆ that a    ┆ at, 31    ┆ 3         ┆ n",      │
│           ┆           ┆           ┆ Stirling  ┆   ┆ determina ┆ Mar 2007  ┆           ┆ "David", │
│           ┆           ┆           ┆ cycl…     ┆   ┆ nt o…     ┆ 03:16…    ┆           ┆ ""]]     │
│ 0704.0005 ┆ Alberto   ┆ Wael Abu- ┆ From      ┆ … ┆ In this   ┆ [{"v1","M ┆ 2013-10-1 ┆ [["Abu-S │
│           ┆ Torchinsk ┆ Shammala  ┆ dyadic    ┆   ┆ paper we  ┆ on, 2 Apr ┆ 5         ┆ hammala" │
│           ┆ y         ┆ and       ┆ $\Lambda_ ┆   ┆ show how  ┆ 2007      ┆           ┆ ,        │
│           ┆           ┆ Alberto … ┆ {\alpha}$ ┆   ┆ to…       ┆ 18:09:…   ┆           ┆ "Wael",  │
│           ┆           ┆           ┆ …         ┆   ┆           ┆           ┆           ┆ ""],…    │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [12]:
np.unpackbits(df.head().collect()["packed_qjl_bits"].to_numpy(), axis=-1)

array([[0, 0, 0, ..., 0, 1, 1],
       [0, 0, 1, ..., 1, 0, 0],
       [0, 0, 0, ..., 1, 1, 1],
       [0, 0, 0, ..., 0, 1, 1],
       [0, 1, 1, ..., 1, 0, 1]], shape=(5, 512), dtype=uint8)